name: Artifact Workflow
on:
    push:
        branches:
            - main
            - development
    workflow_dispatch:

jobs:
    uploadArtifact:
        runs-on: ubuntu-latest
        steps:
            - name: Run test case
              uses: actions/checkout@v4
            
              
            - name: Set up python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'
                
            - name: Install pip
              run: |
                echo "Install pip..."
                python -m pip install --upgrade pip
                
            - name: Set up cache
              uses: actions/cache@v4
              with:
                path:  ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                
            - name: Install dependencies
              run: pip install -r requirements.txt
            
            - name: Run Django tests
              run: python manage.py test crudapp

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                name: artifact-file
                path: artifact

            - name: Print Uploaded Artifact
              run: echo "Artifact uploaded successfully!"
    
    downloadArtifact:
        runs-on: ubuntu-latest
        needs: uploadArtifact
        steps:
            - name: Download Artifact
              uses: actions/download-artifact@v4
              with:
                name: artifact-file
                path: artifact

            - name: Print Downloaded Artifact
              run: echo "Artifact downloaded successfully!"