name: Artifact Workflow
on:
    push:
        branches:
            - main
            - development
    workflow_dispatch:

jobs:
    uploadArtifact:
        runs-on: ubuntu-latest
        steps:
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                name: artifact-file
                path: artifact
            - name: Print Uploaded Artifact
              run: echo "Artifact uploaded successfully!"
    
    downloadArtifact:
        runs-on: ubuntu-latest
        needs: uploadArtifact
        steps:
            - name: Download Artifact
              uses: actions/download-artifact@v4
              with:
                name: artifact-file
                path: artifact
            - name: Print Downloaded Artifact
              run: echo "Artifact downloaded successfully!"