name: Clone repo at runner matchin and deploy dist
on: [push,workflow_dispatch ]
jobs:
    deployDist:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              run: |
                echo "Clone repo..."
                echo "${{toJson(github)}}"
                git clone https://github.com/${{github.repository}}.git