name: Test case
# on: [push,workflow_dispatch]
on:
    push:
        branches:
            - main
            - development
    workflow_dispatch:

jobs:
    testCase:
        runs-on: ubuntu-latest
        steps:
            - name: Run test case
              uses: actions/checkout@v4
            
            - name: Set up cache
              uses: actions/cache@v4
              with:
                path:  ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

            - name: Set up python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'
            
            - name: Install pip
              run: |
                echo "Install pip..."
                python -m pip install --upgrade pip

            - name: Install dependencies
              run: pip install -r requirements.txt
            
            - name: Run Django tests
              run: python manage.py test crudapp

    multiJobs:
        runs-on: ubuntu-latest
        needs: testCase
        steps:
            - name: Running multi jobs
              uses: actions/checkout@v4
            
            - name: Set up cache
              uses: actions/cache@v4
              with:
                path:  ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

            - name: Set up python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'
            
            - name: Install pip 
              run: python -m pip install --upgrade pip
            
            - name: Install dependencies
              run: pip install -r requirements.txt
            
            - name: print message
              run: echo "This is multi jobs practice in GitHub CI/CD workflow."